name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-preview.2.20176.6
      - name: Install PeachPieTemplates
        run: dotnet new -i Peachpie.Templates::*
      - name: Build
        run: dotnet build peachpie-sabre/sabre.net.sln
      # - name: Pack
      #  run: dotnet Pack peachpie-sabre/sabre.net.sln
      - name: publish to nuget
        run: dotnet nuget push peachpie-sabre/bin/Debug/sabre.net.1.0.0.nupkg -k  ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
